### PR TITLE
you mention two subjects in same sentence, so use plural

### PR DESCRIPTION
**Pull request by vsopvsop**

### CODE REVIEW

**Comment by derberg** [comment]
@vsopvsop after previous merges this pull requests has conflict. Please make a change in "with you me recent discoveries" to "with you my recent discoveries" and this should do the trick

**Comment by vsopvsop** [comment]
Yes Sir. I've done it. Thanks.

**Comment by derberg** [comment]
I still cannot merge it in, still conflicts.

**Comment by derberg** [comment]
@vsopvsop the biggest problem is that you are suggesting changes in the generated content. The whole content of this repository is generated with docpad and with my next release, everything you've suggested and I merged in, will be lost. The source documents are stored here https://github.com/derberg/blog-docpad-learn

**Comment by vsopvsop** [comment]
Respected Sir, I am a newbie to github. 
Please forgive my little errors. 
I have noted your source documents' github page. I was not aware of that particular page earlier.
I am closing this pull request to be generated again.

**Pull request closed without merging**
