### PR TITLE
software - correct spelling

### PR DESCRIPTION
**Pull request by vsopvsop**

### CODE REVIEW

**Comment by derberg** [comment]
@vsopvsop some conflicts here, I guess it is because of "usally" that was changed in another pull request to "usually"

I would suggest to make all the changes for one file in one pull requests, otherwise these conflicts will repeat.

**Comment by vsopvsop** [comment]
Respected Sir, I've noted your point. I am closing this pull request to generate the same again in source document repository. You have informed me elsewhere that all these merges will be lost on next generation of website since I am doing it on output website and not on source.

I am really sorry to have wasted your time thus.

I will try to combine all merges for same document in single pull request. But It is not easy due to my approach.

**Comment by derberg** [comment]
You didn't waste my time at all. I'm super happy and grateful for your contribution. I miss a proof reader for my posts. I will port all your fixes, that I've merged, to the sources repository. And if it comes to you, please submit all additional pull requests in the source branch

**Comment by vsopvsop** [comment]
Respected sir, I've noted your point. 
// I miss a proof reader for my posts. //
Many online spell checkers are available.
Thanks.

**Pull request closed without merging**
